# Generated by Django 6.0.1 on 2026-02-02 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_visitorschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorschedule',
            old_name='reschdueled_time',
            new_name='rescheduled_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visitor_id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitorschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20),
        ),
    ]
