# Generated by Django 6.0.1 on 2026-02-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_reschdueled_time_visitorschedule_rescheduled_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='status',
        ),
    ]
